package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date test;

	private java.lang.Double test2;

	public test() {
	}

	public java.util.Date getTest() {
		return this.test;
	}

	public void setTest(java.util.Date test) {
		this.test = test;
	}

	public java.lang.Double getTest2() {
		return this.test2;
	}

	public void setTest2(java.lang.Double test2) {
		this.test2 = test2;
	}

	public test(java.util.Date test, java.lang.Double test2) {
		this.test = test;
		this.test2 = test2;
	}

}