package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date test;

	private java.lang.Double test2;

	private java.util.Date test4;

	private java.lang.Double test5;

	private java.lang.Byte test6;

	public test() {
	}

	public java.util.Date getTest() {
		return this.test;
	}

	public void setTest(java.util.Date test) {
		this.test = test;
	}

	public java.lang.Double getTest2() {
		return this.test2;
	}

	public void setTest2(java.lang.Double test2) {
		this.test2 = test2;
	}

	public java.util.Date getTest4() {
		return this.test4;
	}

	public void setTest4(java.util.Date test4) {
		this.test4 = test4;
	}

	public java.lang.Double getTest5() {
		return this.test5;
	}

	public void setTest5(java.lang.Double test5) {
		this.test5 = test5;
	}

	public java.lang.Byte getTest6() {
		return this.test6;
	}

	public void setTest6(java.lang.Byte test6) {
		this.test6 = test6;
	}

	public test(java.util.Date test, java.lang.Double test2,
			java.util.Date test4, java.lang.Double test5, java.lang.Byte test6) {
		this.test = test;
		this.test2 = test2;
		this.test4 = test4;
		this.test5 = test5;
		this.test6 = test6;
	}

}