package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class test implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.Date test;

	public test() {
	}

	public java.util.Date getTest() {
		return this.test;
	}

	public void setTest(java.util.Date test) {
		this.test = test;
	}

	public test(java.util.Date test) {
		this.test = test;
	}

}